[package]
name = "octopus-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
prost = { workspace = true }
tonic = { workspace = true }

[build-dependencies]

rustc_version = "0.4.0"
fs-err = "3.1.0"
tonic-build = { workspace = true }
walkdir = "2"